const appTypes = {
  SET_DEFAULT_HOME_PAGE_ITEMS: "SET_DEFAULT_HOME_PAGE_ITEMS",
  SET_ITEMS: "SET_ITEMS",
  SET_FOCUS: "SET_FOCUS",
  SET_TRASH: "SET_TRASH",
  SET_TRASH_ICON: "SET_TRASH_ICON",
};

export default appTypes;
