const activeTypes = {
  SET_APP_ACTIVE_SETTINGS: "SET_APP_ACTIVE_SETTINGS",
  SET_APP_ACTIVE_REMOVE: "SET_APP_ACTIVE_REMOVE",
  UPDATE_APP_ACTIVE_SETTINGS: "UPDATE_APP_ACTIVE_SETTINGS",
  UPDATE_APP_ACTIVE_ZINDEX: "UPDATE_APP_ACTIVE_ZINDEX",
  UPDATE_APP_ACTIVE_OFFSET: "UPDATE_APP_ACTIVE_OFFSET",
  UPDATE_APP_ACTIVE_MAXIMIZE: "UPDATE_APP_ACTIVE_MAXIMIZE",
};

export default activeTypes;
