const activeTypes = {
  SET_APP_ACTIVE_SETTINGS: "SET_APP_ACTIVE_SETTINGS",
  SET_APP_ACTIVE_REMOVE: "SET_APP_ACTIVE_REMOVE",
  UPDATE_APP_ACTIVE_SETTINGS: "UPDATE_APP_ACTIVE_SETTINGS",
};

export default activeTypes;
